version: '3.8'
services:
  botpress:
    image: botpress/server:v12_26_6
    environment:
      BP_PRODUCTION: 'true'
      BP_HTTP_PORT: '3000'
    ports:
      - "3000:3000"
    volumes:
      - data:/botpress/data
    restart: always

volumes:
  data:
